### ISSUE TITLE
Unicode Encoding Error (UnicodeEncodeError) on CentOS with Docker

### ISSUE THREAD

**Issue by eblen** [pharmai/plip#111]
On CentOS 7.9.2009, I sometimes receive an encoding error when running PLIP with Docker. This happens when I try to print help (-h) or generate a text report (-t).

I tried importing numerous environment variables with the -env flag to docker (LANG, PYTHONIOENCODING, LC_ALL, etc.), but the problem persists. Here is a sample run:

<pre>
>docker run --rm -v /home/user/work:/results -w /results pharmai/plip:latest -h
Traceback (most recent call last):
  File "/src/plip/plipcmd.py", line 313, in <module>
    main()
  File "/src/plip/plipcmd.py", line 244, in main
    arguments = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1033, in __call__
    parser.print_help()
  File "/usr/lib/python3.6/argparse.py", line 2375, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.6/argparse.py", line 2381, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 679: ordinal not in range(128)
</pre>

**Comment by fkaiserbio** [comment]
Thank you for reporting this! It was accidentally introduces by copy and pasting an invalid character for the new citation information.
