### ISSUE TITLE
Traceback (most recent call last):   File "/plip/plip/plipcmd.py", line 16, in <module>     from plip.basic import config, logger ModuleNotFoundError: No module named 'plip'

### ISSUE THREAD

**Issue by MarcAmil30** [pharmai/plip#132]
**Describe the bug**
When following the documentation of plip. It states to simplify access to plip by ```$ alias plip= `python` <absolute path>/plip/plipcmd.py```.  When inputting this into the terminal and running ```plip```.  I get the error.

```
Traceback (most recent call last):
  File "<absolute path>/plip/plip/plipcmd.py", line 16, in <module>
    from plip.basic import config, logger
ModuleNotFoundError: No module named 'plip'
```

I wanted to ask how to solve this issue? 

**Expected behavior**
I expected ```plipcmd.py```code to run without any error. 

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser = chrome

**Comment by fkaiserbio** [comment]
Hi,

please provide details on how you've installed PLIP. What is your `PYTHONPATH` environment variable? Did you try the Docker version of PLIP, it will make it very easy to use.
