### ISSUE TITLE
./plip.simg -i 1vsn -yv

### ISSUE THREAD

**Issue by UnixJunkie** [pharmai/plip#159]
The singularity container is not working for me:

# ./plip.simg -i 1vsn -yv
WARNING: underlay of /etc/localtime required more than 50 (110) bind mounts
==============================
*** Open Babel Error  in LoadAllPlugins
  Unable to find OpenBabel plugins. Try setting the BABEL_LIBDIR environment variable.
Traceback (most recent call last):
  File "/src/plip/plipcmd.py", line 23, in <module>
    from plip.exchange.report import StructureReport
  File "/src/plip/exchange/report.py", line 8, in <module>
    from plip.structure.preparation import PDBComplex
  File "/src/plip/structure/preparation.py", line 9, in <module>
    from openbabel import pybel
  File "/usr/local/lib/python3.6/dist-packages/openbabel/pybel.py", line 87, in <module>
    informats = _formatstodict(_obconv.GetSupportedInputFormat())
  File "/usr/local/lib/python3.6/dist-packages/openbabel/pybel.py", line 66, in _formatstodict
    broken = [(x, y.strip()) for x, y in broken]
  File "/usr/local/lib/python3.6/dist-packages/openbabel/pybel.py", line 66, in <listcomp>
    broken = [(x, y.strip()) for x, y in broken]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by mestia** [comment]
Hi,
first, the warning about `/etc/localtime` I believe can be ignored.
The real problem is most likely your local environment.
Try to run singularity with --no-home or --containeall (-C) flags
for example:
```
cd /tmp/
singularity exec --no-home ~/plip_v2.3.0.simg python3 /src/plip/plipcmd.py  -i 1vsn -yv
```

See this link for more details: https://docs.sylabs.io/guides/latest/user-guide/bind_paths_and_mounts.html
