### ISSUE TITLE
TypeError: '<' not supported between instances of 'Atom' and 'Atom' with Python 3

### ISSUE THREAD

**Issue by xrobin** [pharmai/plip#53]
Running the current 'stable' branch from GitHub, Python 3.6.6 and OpenBabel 2.4.1, it seems that PLIP fails on water bridges:
```
$ python plip/plipcmd.py -i 3GKR
Traceback (most recent call last):
  File "plip/plipcmd.py", line 311, in <module>
    main_init()
  File "plip/plipcmd.py", line 307, in main_init
    main(expanded_path, arguments.pdbid)  # Start main script
  File "plip/plipcmd.py", line 171, in main
    process_pdb(pdbpath, config.OUTPATH, outputprefix=outputprefix)
  File "plip/plipcmd.py", line 66, in process_pdb
    mol.characterize_complex(ligand)
  File "/scicore/home/schwede/zohixe92/projects/plip/plip/modules/preparation.py", line 1439, in characterize_complex
    pli_obj = PLInteraction(lig_obj, bs_obj, self)
  File "/scicore/home/schwede/zohixe92/projects/plip/plip/modules/preparation.py", line 628, in __init__
    self.water_bridges = self.refine_water_bridges(self.water_bridges, self.hbonds_ldon, self.hbonds_pdon)
  File "/scicore/home/schwede/zohixe92/projects/plip/plip/modules/preparation.py", line 865, in refine_water_bridges
    wb_dict2[water] = sorted(wb_dict2[water])
TypeError: '<' not supported between instances of 'Atom' and 'Atom'
```

This affects apparently a lot of entries from the PDB, a quick stats from our side indicates around 30% of new entries. To cite a few: 3EMS, 4CUM, 5DDR, 1D7P, 6R79.

**Comment by fkaiserbio** [comment]
fixed in 19b45787d17ea562d354bacc40c4c1bb7be14328
