### ISSUE TITLE
ModuleNotFoundError: No module named 'plip.basic'

### ISSUE THREAD

**Issue by xrobin** [pharmai/plip#60]
I am trying to install the latest PLIP beta on Ubuntu 19.10. I'm using an apt-get installed python 3.7.5, and a manually compiled and installed OpenBabel 3.1.1.

Then I tried to install the beta PLIP:
```
$ git checkout tags/v2.1.0-beta
$ python3 setup.py install --user
/usr/lib/python3/dist-packages/setuptools/dist.py:474: UserWarning: Normalizing '2.1.0-beta' to '2.1.0b0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing plip.egg-info/PKG-INFO
writing dependency_links to plip.egg-info/dependency_links.txt
writing requirements to plip.egg-info/requires.txt
writing top-level names to plip.egg-info/top_level.txt
reading manifest file 'plip.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'plip.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/plip
copying plip/plipcmd.py -> build/lib/plip
copying plip/__init__.py -> build/lib/plip
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/plip
copying build/lib/plip/plipcmd.py -> build/bdist.linux-x86_64/egg/plip
copying build/lib/plip/__init__.py -> build/bdist.linux-x86_64/egg/plip
byte-compiling build/bdist.linux-x86_64/egg/plip/plipcmd.py to plipcmd.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/plip/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.7
copying and adjusting plip/plipcmd.py -> build/scripts-3.7
changing mode of build/scripts-3.7/plipcmd.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/plipcmd.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/plipcmd.py to 755
copying plip.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying plip.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying plip.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying plip.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying plip.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying plip.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/plip-2.1.0b0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing plip-2.1.0b0-py3.7.egg
creating /home/xavier/.local/lib/python3.7/site-packages/plip-2.1.0b0-py3.7.egg
Extracting plip-2.1.0b0-py3.7.egg to /home/xavier/.local/lib/python3.7/site-packages
Adding plip 2.1.0b0 to easy-install.pth file
Installing plipcmd.py script to /home/xavier/.local/bin

Installed /home/xavier/.local/lib/python3.7/site-packages/plip-2.1.0b0-py3.7.egg
Processing dependencies for plip==2.1.0b0
Searching for pymol==2.2.0
Best match: pymol 2.2.0
Adding pymol 2.2.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for openbabel==3.1.0
Best match: openbabel 3.1.0
Adding openbabel 3.1.0 to easy-install.pth file

Using /home/xavier/.local/lib/python3.7/site-packages
Searching for numpy==1.16.2
Best match: numpy 1.16.2
Adding numpy 1.16.2 to easy-install.pth file
Installing f2py script to /home/xavier/.local/bin
Installing f2py3 script to /home/xavier/.local/bin
Installing f2py3.7 script to /home/xavier/.local/bin

Using /usr/lib/python3/dist-packages
Searching for lxml==4.5.0
Best match: lxml 4.5.0
Adding lxml 4.5.0 to easy-install.pth file

Using /home/xavier/.local/lib/python3.7/site-packages
Finished processing dependencies for plip==2.1.0b0
```

As indicated by the log, plipcmd.py is correctly installed in /home/xavier/.local/bin. However it doesn't work:

```
$ which plipcmd.py
/home/xavier/.local/bin/plipcmd.py
$ plipcmd.py 
Traceback (most recent call last):
  File "/home/xavier/.local/bin/plipcmd.py", line 4, in <module>
    __import__('pkg_resources').run_script('plip==2.1.0b0', 'plipcmd.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/xavier/.local/lib/python3.7/site-packages/plip-2.1.0b0-py3.7.egg/EGG-INFO/scripts/plipcmd.py", line 16, in <module>
    from plip.basic import config, logger
ModuleNotFoundError: No module named 'plip.basic'
```

It looks like there was a problem during the installation, and some python files weren't copied. The `plip` folder within the egg is nearly empty:

```
$ ls /home/xavier/.local/lib/python3.7/site-packages/plip-2.1.0b0-py3.7.egg/plip/
__init__.py  __pycache__  plipcmd.py
```

And there is no `plip` folder directly in `site-packages`

```
$ ls /home/xavier/.local/lib/python3.7/site-packages/plip
ls: cannot access '/home/xavier/.local/lib/python3.7/site-packages/plip': No such file or directory
```

I'm not sure what's going on and how to proceed. Please let me know if you need any additional information to help solve the issue.

**Comment by xrobin** [comment]
Note that I can reproduce with MacOS 10.15.4 with homebrew open-babel 3.1.1 (bottled) and python 3.8.2.
